name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17, 1.18, 1.19 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go }}"
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check Go formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
              gofmt -s -l .
              exit 1
          fi
      - name: Check Go imports
        run: |
          if [ "$(goimports -d . | wc -l)" -gt 0 ]; then
          goimports -d .
          exit 1
          fi
      - name: Run Go vet
        run: go vet ./...
      - name: Run Go test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
